// ── Markdown Export ────────────────────────────────────────────────
//
// Generates a Markdown report from scan results, suitable for
// saving to disk or pasting into an issue tracker.

import type { CliOptions, ScanResult, Severity } from "../types";

// ── Helpers ────────────────────────────────────────────────────────

function severityEmoji(severity: Severity): string {
  switch (severity) {
    case "critical": {
      return "🚨";
    }
    case "performance": {
      return "🚀";
    }
    case "best-practice": {
      return "💡";
    }
    case "info": {
      return "ℹ️";
    }
  }
}

function severityHeading(severity: Severity): string {
  switch (severity) {
    case "critical": {
      return "Critical — Must fix now";
    }
    case "performance": {
      return "Performance — Causes slowdowns";
    }
    case "best-practice": {
      return "Best Practices — Recommended improvements";
    }
    case "info": {
      return "Info — For your awareness";
    }
  }
}

// ── Export ──────────────────────────────────────────────────────────

export async function exportToMarkdown(
  result: ScanResult,
  filePath: string,
  options?: CliOptions
): Promise<void> {
  const filter = options?.severityFilter;
  const hasFilter = filter && filter.size > 0;
  const lines: string[] = [];

  lines.push("# React Triage Report");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`| ------ | ----- |`);
  lines.push(`| Health Score | **${result.score}/100** |`);
  lines.push(`| Scan Time | ${result.timeTaken}ms |`);
  lines.push(`| Files Scanned | ${result.stats.totalFiles} |`);
  lines.push(`| Total Issues | ${result.issues.length} |`);
  lines.push(`| Vulnerabilities | ${result.securityAudit.summary.total} |`);
  lines.push("");

  // Group by severity
  const severities: Severity[] = ["critical", "performance", "best-practice", "info"];

  for (const severity of severities) {
    if (hasFilter && !filter.has(severity)) {
      continue;
    }

    const group = result.issues.filter((issue) => issue.severity === severity);
    if (group.length === 0) {
      continue;
    }

    lines.push(`## ${severityEmoji(severity)} ${severityHeading(severity)} (${group.length})`);
    lines.push("");

    for (const issue of group) {
      const location = issue.file ? ` — \`${issue.file}:${issue.line}\`` : "";
      lines.push(`- **${issue.rule}**: ${issue.message}${location}`);
      if (issue.help) {
        lines.push(`  - 💊 ${issue.help}`);
      }
    }

    lines.push("");
  }

  // Dependency issues
  if (result.dependencyIssues.length > 0) {
    lines.push("## 📦 Dependency Issues");
    lines.push("");
    for (const dep of result.dependencyIssues) {
      lines.push(`- **${dep.type}**: ${dep.message}`);
    }
    lines.push("");
  }

  // Security vulnerabilities
  if (result.securityAudit.summary.total > 0) {
    const { summary, vulnerabilities } = result.securityAudit;
    const parts: string[] = [];
    if (summary.critical > 0) parts.push(`${summary.critical} critical`);
    if (summary.high > 0) parts.push(`${summary.high} high`);
    if (summary.moderate > 0) parts.push(`${summary.moderate} moderate`);
    if (summary.low > 0) parts.push(`${summary.low} low`);

    lines.push(`## 🔒 Security Vulnerabilities (${parts.join(", ")})`);
    lines.push("");
    lines.push("| Severity | Package | Vulnerability | CVSS | Advisory |");
    lines.push("| -------- | ------- | ------------- | ---- | -------- |");

    for (const vuln of vulnerabilities) {
      const cvss = vuln.cvssScore !== null ? String(vuln.cvssScore) : "-";
      const link = vuln.url ? `[View](${vuln.url})` : "-";
      lines.push(`| ${vuln.severity.toUpperCase()} | \`${vuln.package}\` | ${vuln.title} | ${cvss} | ${link} |`);
    }

    lines.push("");
    lines.push("> 💊 Run `bun update` or `bun update --latest` to fix vulnerable packages.");
    lines.push("");
  }

  // Large files
  if (result.stats.largeFiles.length > 0) {
    lines.push("## 📏 Large Files");
    lines.push("");
    for (const file of result.stats.largeFiles) {
      lines.push(`- \`${file.file}\` — ${file.lines} lines`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by react-triage on ${new Date().toISOString().slice(0, 10)}*`);
  lines.push("");

  await Bun.write(filePath, lines.join("\n"));
}
